language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t lunaticpraveen/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true lunaticpraveen/react-test npm run test

after_success: 
  - docker build -t lunaticpraveen/multi-client ./client
  - docker build -t lunaticpraveen/multi-nginx ./nginx
  - docker build -t lunaticpraveen/multi-server ./server
  - docker build -t lunaticpraveen/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push lunaticpraveen/multi-client 
  - docker push lunaticpraveen/multi-nginx
  - docker push lunaticpraveen/multi-server
  - docker push lunaticpraveen/multi-worker